[package]
name = "mur-channel"
version.workspace = true
edition.workspace = true

[dependencies]
mur-common = { path = "../mur-common" }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
fs2 = { workspace = true }
rusqlite = { workspace = true }
uuid = { workspace = true }
notify = { workspace = true }

[dev-dependencies]
tempfile = "3"
