//! Per-agent OS stub generation — spec §5.
//!
//! After Hub imports a `.muragent`, it calls `generate()` to create a
//! platform-native "stub" (macOS `.app`, Windows `.lnk`, Linux `.desktop`)
//! that gives the agent its own Dock/taskbar/launcher identity and registers
//! its URL scheme.
//!
//! Stubs are generated by signed Hub code on the local machine, so they never
//! receive a quarantine xattr — Gatekeeper / SmartScreen don't gate them
//! (spec §3.2). On macOS, the Gatekeeper validation gate in §12.4 is run after
//! every generation to catch regressions early.

use anyhow::Result;
use std::path::{Path, PathBuf};

#[cfg(target_os = "macos")]
pub mod macos;

#[cfg(target_os = "windows")]
pub mod windows;

#[cfg(target_os = "linux")]
pub mod linux;

/// Result of a successful stub generation.
pub struct StubInfo {
    /// Filesystem path to the generated stub (`.app`, `.lnk`, or `.desktop`).
    pub path: PathBuf,
    /// URL scheme registered for this agent, e.g. `muragent-coach`.
    pub url_scheme: String,
}

/// Generate (or regenerate) the OS stub for an agent after import.
///
/// Idempotent: removes any existing stub before creating a fresh one.
/// Called from Hub's `install_inner()` immediately after `installer::install()`
/// returns success.
pub fn generate(
    slug: &str,
    display_name: &str,
    bundle_id: &str,
    url_scheme: &str,
    icon_icns: Option<&[u8]>,
    hub_version: &str,
    mur_home: &Path,
) -> Result<StubInfo> {
    #[cfg(target_os = "macos")]
    return macos::generate(slug, display_name, bundle_id, url_scheme, icon_icns, hub_version, mur_home);

    #[cfg(target_os = "windows")]
    return windows::generate(slug, display_name, bundle_id, url_scheme, icon_icns, hub_version, mur_home);

    #[cfg(target_os = "linux")]
    return linux::generate(slug, display_name, bundle_id, url_scheme, icon_icns, hub_version, mur_home);

    #[cfg(not(any(target_os = "macos", target_os = "windows", target_os = "linux")))]
    {
        let _ = (slug, display_name, bundle_id, url_scheme, icon_icns, hub_version, mur_home);
        anyhow::bail!("stub generation not implemented for this platform");
    }
}
