//! Stage runner. Deterministic stages run here; LLM/eval stages are trait hooks
//! (no-op default impl in Plan 1, real impls in Plans 2-3).
use crate::agent_wizard::catalog::RoleManifest;
use crate::agent_wizard::draft::*;
use crate::agent_wizard::entitlements::preset_for;

/// Driver-supplied hooks. Plan 1 uses the no-op defaults (deterministic, no LLM).
pub trait WizardHooks {
    fn on_progress(&mut self, _p: &Progress) {}
    /// Return Some(skills) to override stub skills (LLM author stage, Plan 2).
    fn author_skills(&mut self, _role: &RoleSpec, _topics: &[String]) -> Option<Vec<SkillDraft>> {
        None
    }
    /// Return Some(markdown) to override the template prompt (LLM stage, Plan 2).
    fn draft_prompt(&mut self, _role: &RoleSpec) -> Option<String> {
        None
    }
    /// The review gate: return the (possibly edited) draft to approve, or None to abort.
    fn review_gate(&mut self, draft: WizardDraft) -> Option<WizardDraft> {
        Some(draft)
    }
}

fn stub_skill_yaml(topic: &str, role: &RoleSpec) -> String {
    let name = &role.name;
    let dn = &role.display_name;
    // Build the YAML with explicit line construction to avoid Rust's `\` line-continuation
    // stripping leading whitespace from indented YAML fields.
    [
        format!("name: {topic}"),
        "version: 1.0.0".into(),
        format!("publisher: human:{name}"),
        "description: >".into(),
        format!("  Skill stub for {topic} ({dn}). Fill with imperative rules, each with a why."),
        "category: context".into(),
        "hosts: [mur-agent]".into(),
        "priority: normal".into(),
        format!("tags: [{name}]"),
        "triggers:".into(),
        "  - type: session_start".into(),
        "  - type: command".into(),
        format!("    pattern: /{topic}"),
        "content:".into(),
        "  abstract: >".into(),
        format!("    TODO (Plan 2 LLM author stage fills this): {topic}."),
        "  context: |".into(),
        format!("    # {topic}"),
        "    Stub generated by `mur agent wizard --no-llm`. Edit at the review gate.".into(),
    ]
    .join("\n")
        + "\n"
}

fn template_prompt(role: &RoleSpec) -> String {
    format!(
        "# {dn} — {charter}\n\nYou are {dn}. Your attached skills are your standard of \"good\".\n\n\
## Operating discipline\nComplete your role's definition of done before claiming a task done.\n\n\
## Honesty\nYou must never fabricate command or file output. If you can't run a tool or read a file \
this turn, say so and reason from context.\n\n## Watching\nNarrate at a high level for a live human.\n",
        dn = role.display_name,
        charter = role.charter,
    )
}

/// Run deterministic stages 1-5 and assemble the draft. LLM hooks may override
/// skills/prompt; otherwise stubs/templates are used.
pub fn build_draft(
    m: &RoleManifest,
    workspace: &str,
    model_ref: &str,
    hooks: &mut impl WizardHooks,
) -> WizardDraft {
    let role = RoleSpec {
        name: m.id.clone(),
        display_name: m.display_name.clone(),
        charter: m.charter.clone(),
        risk: m.risk,
        preset_id: Some(m.id.clone()),
    };
    hooks.on_progress(&Progress {
        stage: Stage::DefineRole,
        message: format!("role {}", role.name),
    });

    let skills = hooks
        .author_skills(&role, &m.skill_topics)
        .unwrap_or_else(|| {
            m.skill_topics
                .iter()
                .map(|t| SkillDraft {
                    name: t.clone(),
                    yaml: stub_skill_yaml(t, &role),
                })
                .collect()
        });
    hooks.on_progress(&Progress {
        stage: Stage::AuthorSkills,
        message: format!("{} skills", skills.len()),
    });

    let prompt = PromptDraft {
        markdown: hooks
            .draft_prompt(&role)
            .unwrap_or_else(|| template_prompt(&role)),
    };
    hooks.on_progress(&Progress {
        stage: Stage::DraftPrompt,
        message: "prompt drafted".into(),
    });

    let entitlements = preset_for(&role, workspace);
    hooks.on_progress(&Progress {
        stage: Stage::Entitlements,
        message: "entitlements scoped".into(),
    });

    WizardDraft {
        role,
        skills,
        prompt,
        entitlements,
        model_ref: model_ref.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    struct NoopHooks;
    impl WizardHooks for NoopHooks {}

    fn manifest() -> RoleManifest {
        RoleManifest {
            id: "pm".into(),
            display_name: "PM".into(),
            charter: "c".into(),
            risk: RiskLevel::Low,
            category: "product".into(),
            skill_topics: vec!["product-spec-and-prd-writing".into()],
        }
    }

    #[test]
    fn builds_draft_with_stub_skills_and_template_prompt() {
        let draft = build_draft(&manifest(), "/repo", "claude_sonnet", &mut NoopHooks);
        assert_eq!(draft.role.name, "pm");
        assert_eq!(draft.skills.len(), 1);
        assert!(
            draft.skills[0]
                .yaml
                .contains("name: product-spec-and-prd-writing")
        );
        assert!(draft.prompt.markdown.contains("never fabricate"));
        assert_eq!(draft.model_ref, "claude_sonnet");
    }
}
