//! Smart sync — write top patterns to AI tool config files.
//!
//! Supported targets:
//! - .cursorrules (Cursor)
//! - .windsurfrules (Windsurf)
//! - AGENTS.md (Codex/Claude Code)
//! - .aider.conf.yml (Aider)

use anyhow::{Context, Result};
use std::path::Path;

use super::hook::InjectedItem;

/// Sync target configuration.
#[derive(Debug, Clone)]
pub struct SyncTarget {
    pub name: String,
    pub file: String,
    pub format: SyncFormat,
    pub max_patterns: usize,
}

#[derive(Debug, Clone)]
#[allow(dead_code)] // YamlComment for future Aider support
pub enum SyncFormat {
    /// Plain text with headers
    Plaintext,
    /// Markdown with headers
    Markdown,
    /// YAML embedded in comments
    YamlComment,
}

impl Default for SyncTarget {
    fn default() -> Self {
        Self {
            name: "cursorrules".into(),
            file: ".cursorrules".into(),
            format: SyncFormat::Plaintext,
            max_patterns: 20,
        }
    }
}

/// Default sync targets for common AI tools.
pub fn default_targets() -> Vec<SyncTarget> {
    vec![
        SyncTarget {
            name: "cursorrules".into(),
            file: ".cursorrules".into(),
            format: SyncFormat::Plaintext,
            max_patterns: 20,
        },
        SyncTarget {
            name: "windsurfrules".into(),
            file: ".windsurfrules".into(),
            format: SyncFormat::Plaintext,
            max_patterns: 20,
        },
        SyncTarget {
            name: "AGENTS.md".into(),
            file: "AGENTS.md".into(),
            format: SyncFormat::Markdown,
            max_patterns: 20,
        },
    ]
}

/// Generate sync content for items (Skill pathway).
pub fn generate_sync_content_from_items(items: &[InjectedItem], format: &SyncFormat) -> String {
    if items.is_empty() {
        return String::new();
    }
    let marker_start = "<!-- MUR:START - Auto-generated by mur sync. Do not edit this section. -->";
    let marker_end = "<!-- MUR:END -->";
    let mut content = String::new();
    match format {
        SyncFormat::Plaintext => {
            content.push_str("# Learned patterns (auto-synced by mur)\n\n");
            for item in items {
                content.push_str(&format!("## {}\n", item.description));
                content.push_str(&item.content_text);
                content.push_str("\n\n");
            }
        }
        SyncFormat::Markdown => {
            content.push_str(marker_start);
            content.push_str("\n## Learned Patterns\n\n");
            for item in items {
                content.push_str(&format!("### {}\n", item.description));
                content.push_str(&item.content_text);
                content.push_str("\n\n");
            }
            content.push_str(marker_end);
        }
        SyncFormat::YamlComment => {
            content.push_str("# Learned patterns (auto-synced by mur)\n");
            for item in items {
                content.push_str(&format!("# {}: {}\n", item.name, item.description));
            }
        }
    }
    content
}

/// Write sync content to a target file, preserving non-mur content.
///
/// These files are hand-authored (AGENTS.md, .cursorrules): everything outside
/// the MUR markers belongs to the user, and this function is the only thing
/// standing between it and a generated block. Two rules follow from that:
///
/// - **A read failure is never "the file is empty."** `read_to_string` returns
///   Err for a permission problem or an I/O error just as it does for a missing
///   file; treating those alike would replace a full document with the
///   generated block alone. Only `NotFound` means there is nothing to preserve.
/// - **The write is atomic** (temp + rename, the same idiom as the YAML stores),
///   so an interrupted or out-of-space write cannot leave the target truncated.
pub fn write_sync_file(path: &Path, content: &str, format: &SyncFormat) -> Result<()> {
    let marker_start = "<!-- MUR:START - Auto-generated by mur sync. Do not edit this section. -->";
    let marker_end = "<!-- MUR:END -->";

    let existing = match std::fs::read_to_string(path) {
        Ok(s) => s,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => String::new(),
        Err(e) => {
            return Err(
                anyhow::Error::new(e).context(format!("read {} before sync", path.display()))
            );
        }
    };

    let output = match format {
        SyncFormat::Markdown => {
            // Replace between markers, or append. `end > start` guards a file
            // whose markers were reordered by hand: splicing on a backwards
            // pair would duplicate the span between them instead of replacing
            // it, so treat that as "no usable block" and append.
            match (existing.find(marker_start), existing.find(marker_end)) {
                (Some(start), Some(end)) if end > start => {
                    let end = end + marker_end.len();
                    format!("{}{}{}", &existing[..start], content, &existing[end..])
                }
                _ if existing.is_empty() => content.to_string(),
                _ => format!("{}\n\n{}", existing.trim_end(), content),
            }
        }
        _ => {
            // Overwrite entirely for plaintext/yaml
            content.to_string()
        }
    };

    let tmp = path.with_extension("mur-sync.tmp");
    std::fs::write(&tmp, output).with_context(|| format!("write {}", tmp.display()))?;
    std::fs::rename(&tmp, path).with_context(|| format!("replace {}", path.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::inject::hook::{InjectedItem, KindGroup};

    fn make_item(desc: &str) -> InjectedItem {
        InjectedItem {
            name: "test".into(),
            description: desc.into(),
            content_text: "Do the thing".into(),
            kind_group: KindGroup::Knowledge,
        }
    }

    #[test]
    fn test_plaintext_format() {
        let items = vec![make_item("Use foo")];
        let content = generate_sync_content_from_items(&items, &SyncFormat::Plaintext);
        assert!(content.contains("# Learned patterns"));
        assert!(content.contains("## Use foo"));
    }

    #[test]
    fn test_markdown_format_with_markers() {
        let items = vec![make_item("Use bar")];
        let content = generate_sync_content_from_items(&items, &SyncFormat::Markdown);
        assert!(content.contains("MUR:START"));
        assert!(content.contains("MUR:END"));
        assert!(content.contains("### Use bar"));
    }

    #[test]
    fn test_write_preserves_existing() {
        let tmp = tempfile::TempDir::new().unwrap();
        let path = tmp.path().join("AGENTS.md");

        // Write initial content
        std::fs::write(&path, "# My Project\n\nSome existing content.\n").unwrap();

        let items = vec![make_item("Pattern A")];
        let content = generate_sync_content_from_items(&items, &SyncFormat::Markdown);
        write_sync_file(&path, &content, &SyncFormat::Markdown).unwrap();

        let result = std::fs::read_to_string(&path).unwrap();
        assert!(result.contains("My Project"));
        assert!(result.contains("Pattern A"));

        // Write again — should replace mur section
        let items2 = vec![make_item("Pattern B")];
        let content2 = generate_sync_content_from_items(&items2, &SyncFormat::Markdown);
        write_sync_file(&path, &content2, &SyncFormat::Markdown).unwrap();

        let result2 = std::fs::read_to_string(&path).unwrap();
        assert!(result2.contains("My Project"));
        assert!(result2.contains("Pattern B"));
        assert!(!result2.contains("Pattern A")); // replaced
    }

    /// A file we cannot READ must never be replaced. `read_to_string` fails the
    /// same way for a permission error as for a missing file, and treating the
    /// two alike swaps a hand-written document for the generated block alone —
    /// silent, total loss of the part of the file that is not ours.
    #[test]
    #[cfg(unix)]
    fn unreadable_target_is_refused_not_overwritten() {
        use std::os::unix::fs::PermissionsExt;

        let tmp = tempfile::TempDir::new().unwrap();
        let path = tmp.path().join("AGENTS.md");
        let original = "# My Project\n\nHand-written guidance.\n";
        std::fs::write(&path, original).unwrap();
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o000)).unwrap();

        let content =
            generate_sync_content_from_items(&[make_item("Pattern A")], &SyncFormat::Markdown);
        let err = write_sync_file(&path, &content, &SyncFormat::Markdown).unwrap_err();
        assert!(err.to_string().contains("before sync"), "{err}");

        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o644)).unwrap();
        assert_eq!(
            std::fs::read_to_string(&path).unwrap(),
            original,
            "a failed read must leave the file untouched"
        );
    }

    /// Reordered markers must not splice: `&existing[..start] + content +
    /// &existing[end..]` on a backwards pair duplicates the span between them
    /// instead of replacing it. Append instead — worst case is a stale block
    /// the user can delete, not mangled content.
    #[test]
    fn reversed_markers_append_instead_of_splicing() {
        let tmp = tempfile::TempDir::new().unwrap();
        let path = tmp.path().join("AGENTS.md");
        std::fs::write(
            &path,
            "# My Project\n<!-- MUR:END -->\nstranded\n<!-- MUR:START - Auto-generated by mur sync. Do not edit this section. -->\n",
        )
        .unwrap();

        let content =
            generate_sync_content_from_items(&[make_item("Pattern A")], &SyncFormat::Markdown);
        write_sync_file(&path, &content, &SyncFormat::Markdown).unwrap();

        let result = std::fs::read_to_string(&path).unwrap();
        assert!(result.contains("My Project"), "{result}");
        assert!(result.contains("stranded"), "{result}");
        assert!(result.contains("Pattern A"), "{result}");
    }

    /// The target is replaced by rename, so no reader ever sees a half-written
    /// file and no temp file is left behind.
    #[test]
    fn write_leaves_no_temp_file() {
        let tmp = tempfile::TempDir::new().unwrap();
        let path = tmp.path().join("AGENTS.md");
        std::fs::write(&path, "# My Project\n").unwrap();

        let content =
            generate_sync_content_from_items(&[make_item("Pattern A")], &SyncFormat::Markdown);
        write_sync_file(&path, &content, &SyncFormat::Markdown).unwrap();

        let leftovers: Vec<_> = std::fs::read_dir(tmp.path())
            .unwrap()
            .filter_map(|e| e.ok())
            .map(|e| e.file_name().to_string_lossy().into_owned())
            .filter(|n| n != "AGENTS.md")
            .collect();
        assert!(leftovers.is_empty(), "left behind: {leftovers:?}");
    }
}
