//! Smart sync — write top patterns to AI tool config files.
//!
//! Supported targets:
//! - .cursorrules (Cursor)
//! - .windsurfrules (Windsurf)
//! - AGENTS.md (Codex/Claude Code)
//! - .aider.conf.yml (Aider)

use anyhow::Result;
use std::path::Path;

use super::hook::InjectedItem;

/// Sync target configuration.
#[derive(Debug, Clone)]
pub struct SyncTarget {
    pub name: String,
    pub file: String,
    pub format: SyncFormat,
    pub max_patterns: usize,
}

#[derive(Debug, Clone)]
#[allow(dead_code)] // YamlComment for future Aider support
pub enum SyncFormat {
    /// Plain text with headers
    Plaintext,
    /// Markdown with headers
    Markdown,
    /// YAML embedded in comments
    YamlComment,
}

impl Default for SyncTarget {
    fn default() -> Self {
        Self {
            name: "cursorrules".into(),
            file: ".cursorrules".into(),
            format: SyncFormat::Plaintext,
            max_patterns: 20,
        }
    }
}

/// Default sync targets for common AI tools.
pub fn default_targets() -> Vec<SyncTarget> {
    vec![
        SyncTarget {
            name: "cursorrules".into(),
            file: ".cursorrules".into(),
            format: SyncFormat::Plaintext,
            max_patterns: 20,
        },
        SyncTarget {
            name: "windsurfrules".into(),
            file: ".windsurfrules".into(),
            format: SyncFormat::Plaintext,
            max_patterns: 20,
        },
        SyncTarget {
            name: "AGENTS.md".into(),
            file: "AGENTS.md".into(),
            format: SyncFormat::Markdown,
            max_patterns: 20,
        },
    ]
}

/// Generate sync content for items (Skill pathway).
pub fn generate_sync_content_from_items(items: &[InjectedItem], format: &SyncFormat) -> String {
    if items.is_empty() {
        return String::new();
    }
    let marker_start = "<!-- MUR:START - Auto-generated by mur sync. Do not edit this section. -->";
    let marker_end = "<!-- MUR:END -->";
    let mut content = String::new();
    match format {
        SyncFormat::Plaintext => {
            content.push_str("# Learned patterns (auto-synced by mur)\n\n");
            for item in items {
                content.push_str(&format!("## {}\n", item.description));
                content.push_str(&item.content_text);
                content.push_str("\n\n");
            }
        }
        SyncFormat::Markdown => {
            content.push_str(marker_start);
            content.push_str("\n## Learned Patterns\n\n");
            for item in items {
                content.push_str(&format!("### {}\n", item.description));
                content.push_str(&item.content_text);
                content.push_str("\n\n");
            }
            content.push_str(marker_end);
        }
        SyncFormat::YamlComment => {
            content.push_str("# Learned patterns (auto-synced by mur)\n");
            for item in items {
                content.push_str(&format!("# {}: {}\n", item.name, item.description));
            }
        }
    }
    content
}

/// Write sync content to a target file, preserving non-mur content.
pub fn write_sync_file(path: &Path, content: &str, format: &SyncFormat) -> Result<()> {
    let marker_start = "<!-- MUR:START - Auto-generated by mur sync. Do not edit this section. -->";
    let marker_end = "<!-- MUR:END -->";

    let existing = std::fs::read_to_string(path).unwrap_or_default();

    let output = match format {
        SyncFormat::Markdown => {
            // Replace between markers, or append
            if let (Some(start), Some(end)) =
                (existing.find(marker_start), existing.find(marker_end))
            {
                let end = end + marker_end.len();
                format!("{}{}{}", &existing[..start], content, &existing[end..])
            } else if existing.is_empty() {
                content.to_string()
            } else {
                format!("{}\n\n{}", existing.trim_end(), content)
            }
        }
        _ => {
            // Overwrite entirely for plaintext/yaml
            content.to_string()
        }
    };

    std::fs::write(path, output)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::inject::hook::{InjectedItem, KindGroup};

    fn make_item(desc: &str) -> InjectedItem {
        InjectedItem {
            name: "test".into(),
            description: desc.into(),
            content_text: "Do the thing".into(),
            kind_group: KindGroup::Knowledge,
        }
    }

    #[test]
    fn test_plaintext_format() {
        let items = vec![make_item("Use foo")];
        let content = generate_sync_content_from_items(&items, &SyncFormat::Plaintext);
        assert!(content.contains("# Learned patterns"));
        assert!(content.contains("## Use foo"));
    }

    #[test]
    fn test_markdown_format_with_markers() {
        let items = vec![make_item("Use bar")];
        let content = generate_sync_content_from_items(&items, &SyncFormat::Markdown);
        assert!(content.contains("MUR:START"));
        assert!(content.contains("MUR:END"));
        assert!(content.contains("### Use bar"));
    }

    #[test]
    fn test_write_preserves_existing() {
        let tmp = tempfile::TempDir::new().unwrap();
        let path = tmp.path().join("AGENTS.md");

        // Write initial content
        std::fs::write(&path, "# My Project\n\nSome existing content.\n").unwrap();

        let items = vec![make_item("Pattern A")];
        let content = generate_sync_content_from_items(&items, &SyncFormat::Markdown);
        write_sync_file(&path, &content, &SyncFormat::Markdown).unwrap();

        let result = std::fs::read_to_string(&path).unwrap();
        assert!(result.contains("My Project"));
        assert!(result.contains("Pattern A"));

        // Write again — should replace mur section
        let items2 = vec![make_item("Pattern B")];
        let content2 = generate_sync_content_from_items(&items2, &SyncFormat::Markdown);
        write_sync_file(&path, &content2, &SyncFormat::Markdown).unwrap();

        let result2 = std::fs::read_to_string(&path).unwrap();
        assert!(result2.contains("My Project"));
        assert!(result2.contains("Pattern B"));
        assert!(!result2.contains("Pattern A")); // replaced
    }
}
