//! Smart sync — write top skills to AI tool config files.
//!
//! Supported targets:
//! - .cursorrules (Cursor)
//! - .windsurfrules (Windsurf)
//! - AGENTS.md (Codex/Claude Code)
//! - .aider.conf.yml (Aider)

use anyhow::{Context, Result};
use std::path::Path;

use super::hook::InjectedItem;
use crate::retrieve::skill_candidates::{ActiveScope, LoadedSkill};
use mur_common::skill::stats::LifecycleState;

/// Pick the skills `mur sync` writes into the current repo's AI-tool file.
///
/// Stricter than injection because the output is committed to someone's repo:
/// the same scope gate as `recommend`/`hook` (fleet/project/team skills only
/// where their selector matches), plus a non-zero keyword relevance — the
/// non-relevance weights alone clear the score floor, which let a
/// well-used skill from an unrelated project into this repo's file.
pub fn select_sync_skills(
    mut candidates: Vec<LoadedSkill>,
    query: &str,
    scope: &ActiveScope,
    max: usize,
) -> Vec<InjectedItem> {
    crate::retrieve::skill_candidates::filter_by_scope(&mut candidates, scope);
    crate::retrieve::scoring::score_and_rank_generic(query, candidates)
        .into_iter()
        .filter(|s| s.relevance > 0.0)
        .filter(|s| s.item.stats.lifecycle_state != LifecycleState::Archived)
        .take(max)
        .map(|s| s.item.to_injected_item())
        .collect()
}

/// Sync target configuration.
#[derive(Debug, Clone)]
pub struct SyncTarget {
    pub name: String,
    pub file: String,
    pub format: SyncFormat,
    pub max_patterns: usize,
}

#[derive(Debug, Clone)]
#[allow(dead_code)] // YamlComment for future Aider support
pub enum SyncFormat {
    /// Plain text with headers
    Plaintext,
    /// Markdown with headers
    Markdown,
    /// YAML embedded in comments
    YamlComment,
}

impl Default for SyncTarget {
    fn default() -> Self {
        Self {
            name: "cursorrules".into(),
            file: ".cursorrules".into(),
            format: SyncFormat::Plaintext,
            max_patterns: 20,
        }
    }
}

/// Default sync targets for common AI tools.
pub fn default_targets() -> Vec<SyncTarget> {
    vec![
        SyncTarget {
            name: "cursorrules".into(),
            file: ".cursorrules".into(),
            format: SyncFormat::Plaintext,
            max_patterns: 20,
        },
        SyncTarget {
            name: "windsurfrules".into(),
            file: ".windsurfrules".into(),
            format: SyncFormat::Plaintext,
            max_patterns: 20,
        },
        SyncTarget {
            name: "AGENTS.md".into(),
            file: "AGENTS.md".into(),
            format: SyncFormat::Markdown,
            max_patterns: 20,
        },
    ]
}

/// Generate sync content for items (Skill pathway).
pub fn generate_sync_content_from_items(items: &[InjectedItem], format: &SyncFormat) -> String {
    if items.is_empty() {
        return String::new();
    }
    let marker_start = "<!-- MUR:START - Auto-generated by mur sync. Do not edit this section. -->";
    let marker_end = "<!-- MUR:END -->";
    let mut content = String::new();
    match format {
        SyncFormat::Plaintext => {
            content.push_str("# Learned skills (auto-synced by mur)\n\n");
            for item in items {
                content.push_str(&format!("## {}\n", item.description));
                content.push_str(&item.content_text);
                content.push_str("\n\n");
            }
        }
        SyncFormat::Markdown => {
            content.push_str(marker_start);
            content.push_str("\n## Learned Skills\n\n");
            for item in items {
                content.push_str(&format!("### {}\n", item.description));
                content.push_str(&item.content_text);
                content.push_str("\n\n");
            }
            content.push_str(marker_end);
        }
        SyncFormat::YamlComment => {
            content.push_str("# Learned skills (auto-synced by mur)\n");
            for item in items {
                content.push_str(&format!("# {}: {}\n", item.name, item.description));
            }
        }
    }
    content
}

/// Write sync content to a target file, preserving non-mur content.
///
/// These files are hand-authored (AGENTS.md, .cursorrules): everything outside
/// the MUR markers belongs to the user, and this function is the only thing
/// standing between it and a generated block. Two rules follow from that:
///
/// - **A read failure is never "the file is empty."** `read_to_string` returns
///   Err for a permission problem or an I/O error just as it does for a missing
///   file; treating those alike would replace a full document with the
///   generated block alone. Only `NotFound` means there is nothing to preserve.
/// - **The write is atomic** (temp + rename, the same idiom as the YAML stores),
///   so an interrupted or out-of-space write cannot leave the target truncated.
pub fn write_sync_file(path: &Path, content: &str, format: &SyncFormat) -> Result<()> {
    let marker_start = "<!-- MUR:START - Auto-generated by mur sync. Do not edit this section. -->";
    let marker_end = "<!-- MUR:END -->";

    let existing = match std::fs::read_to_string(path) {
        Ok(s) => s,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => String::new(),
        Err(e) => {
            return Err(
                anyhow::Error::new(e).context(format!("read {} before sync", path.display()))
            );
        }
    };

    let output = match format {
        SyncFormat::Markdown => {
            // Replace between markers, or append. `end > start` guards a file
            // whose markers were reordered by hand: splicing on a backwards
            // pair would duplicate the span between them instead of replacing
            // it, so treat that as "no usable block" and append.
            match (existing.find(marker_start), existing.find(marker_end)) {
                (Some(start), Some(end)) if end > start => {
                    let end = end + marker_end.len();
                    format!("{}{}{}", &existing[..start], content, &existing[end..])
                }
                _ if existing.is_empty() => content.to_string(),
                _ => format!("{}\n\n{}", existing.trim_end(), content),
            }
        }
        _ => {
            // Overwrite entirely for plaintext/yaml
            content.to_string()
        }
    };

    let tmp = path.with_extension("mur-sync.tmp");
    std::fs::write(&tmp, output).with_context(|| format!("write {}", tmp.display()))?;
    std::fs::rename(&tmp, path).with_context(|| format!("replace {}", path.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::inject::hook::{InjectedItem, KindGroup};

    /// A skill loaded through the real manifest parser, with stats that max
    /// out every non-relevance scoring term (just used, always succeeded).
    fn well_used_skill(yaml: &str) -> LoadedSkill {
        let manifest = mur_common::skill::parse_canonical(yaml).expect("fixture parses");
        let now = chrono::Utc::now();
        let mut stats = mur_common::skill::stats::SkillStats::new(&manifest.name, "1.0.0", "", now);
        stats.usage_count = 10;
        stats.success_count = 10;
        stats.last_success_at = Some(now);
        stats.first_successful_use_at = Some(now);
        LoadedSkill { manifest, stats }
    }

    fn skill_yaml(name: &str, desc: &str, tags: &str, scope_lines: &str) -> String {
        format!(
            "name: {name}\nversion: 1.0.0\npublisher: human:test\n\
             description: {desc}\ncategory: context\npriority: critical\n\
             tags: [{tags}]\n{scope_lines}content:\n  abstract: {desc}\n"
        )
    }

    fn names(items: &[InjectedItem]) -> Vec<&str> {
        items.iter().map(|i| i.name.as_str()).collect()
    }

    /// Repro for the www-new AGENTS.md leak: sync must apply the same scope
    /// gate injection does, so a fleet skill or another repo's project skill
    /// never lands in this repo's file — even when it matches the query.
    #[test]
    fn sync_excludes_skills_scoped_to_another_fleet_or_project() {
        let here = "/work/laravel-shop";
        let candidates = vec![
            well_used_skill(&skill_yaml(
                "laravel-migrations",
                "Run artisan migrate for laravel",
                "laravel",
                "",
            )),
            well_used_skill(&skill_yaml(
                "laravel-fleet-router",
                "Route laravel research questions",
                "laravel",
                "scope: fleet\nfleet: deep-research\n",
            )),
            well_used_skill(&skill_yaml(
                "laravel-other-repo",
                "Laravel notes from another repo",
                "laravel",
                "scope: project\nproject: /work/other-repo\n",
            )),
            well_used_skill(&skill_yaml(
                "laravel-this-repo",
                "Laravel notes for this repo",
                "laravel",
                &format!("scope: project\nproject: {here}\n"),
            )),
        ];
        let scope = ActiveScope {
            fleet: None,
            project: Some(here.into()),
            team: None,
        };

        let picked = select_sync_skills(candidates, "laravel", &scope, 20);
        let mut got = names(&picked);
        got.sort_unstable();

        assert_eq!(got, vec!["laravel-migrations", "laravel-this-repo"]);
    }

    /// A skill sharing no keyword with the project can still clear the
    /// score floor on stats alone (the non-relevance weights sum to 0.55,
    /// above the 0.42 floor). Sync writes into a repo file, so it must not.
    #[test]
    fn sync_excludes_skills_with_zero_relevance_to_the_project() {
        let candidates = vec![
            well_used_skill(&skill_yaml(
                "laravel-migrations",
                "Run artisan migrate for laravel",
                "laravel",
                "",
            )),
            well_used_skill(&skill_yaml(
                "go-fly-deploy",
                "Deployed to Fly.io",
                "golang",
                "",
            )),
        ];

        let picked = select_sync_skills(candidates, "laravel", &ActiveScope::default(), 20);

        assert_eq!(names(&picked), vec!["laravel-migrations"]);
    }

    fn make_item(desc: &str) -> InjectedItem {
        InjectedItem {
            name: "test".into(),
            description: desc.into(),
            content_text: "Do the thing".into(),
            kind_group: KindGroup::Knowledge,
        }
    }

    #[test]
    fn test_plaintext_format() {
        let items = vec![make_item("Use foo")];
        let content = generate_sync_content_from_items(&items, &SyncFormat::Plaintext);
        assert!(content.contains("# Learned skills"));
        assert!(content.contains("## Use foo"));
    }

    #[test]
    fn test_markdown_format_with_markers() {
        let items = vec![make_item("Use bar")];
        let content = generate_sync_content_from_items(&items, &SyncFormat::Markdown);
        assert!(content.contains("MUR:START"));
        assert!(content.contains("MUR:END"));
        assert!(content.contains("### Use bar"));
    }

    #[test]
    fn test_write_preserves_existing() {
        let tmp = tempfile::TempDir::new().unwrap();
        let path = tmp.path().join("AGENTS.md");

        // Write initial content
        std::fs::write(&path, "# My Project\n\nSome existing content.\n").unwrap();

        let items = vec![make_item("Pattern A")];
        let content = generate_sync_content_from_items(&items, &SyncFormat::Markdown);
        write_sync_file(&path, &content, &SyncFormat::Markdown).unwrap();

        let result = std::fs::read_to_string(&path).unwrap();
        assert!(result.contains("My Project"));
        assert!(result.contains("Pattern A"));

        // Write again — should replace mur section
        let items2 = vec![make_item("Pattern B")];
        let content2 = generate_sync_content_from_items(&items2, &SyncFormat::Markdown);
        write_sync_file(&path, &content2, &SyncFormat::Markdown).unwrap();

        let result2 = std::fs::read_to_string(&path).unwrap();
        assert!(result2.contains("My Project"));
        assert!(result2.contains("Pattern B"));
        assert!(!result2.contains("Pattern A")); // replaced
    }

    /// The upgrade path every existing user's file takes: their AGENTS.md was
    /// written by an older build and contains `## Learned Patterns` inside the
    /// MUR markers. After a sync it must say `## Learned Skills` with no
    /// leftover of the old heading — otherwise the rename would leave every
    /// synced file carrying both.
    ///
    /// It works because the heading sits INSIDE the markers and
    /// `write_sync_file` splices that whole region. Asserted rather than
    /// reasoned, because the cost of being wrong is a stale line in a file
    /// MUR does not own.
    #[test]
    fn a_resync_replaces_an_older_builds_heading() {
        let tmp = tempfile::TempDir::new().unwrap();
        let path = tmp.path().join("AGENTS.md");
        // Joined rather than one escaped literal: `cargo fmt` collapses a
        // `\`-continued string onto one line and keeps the indentation as
        // real spaces, which would leave the markers indented and the fixture
        // unlike any file a user actually has.
        let existing = [
            "# My Project",
            "",
            "Mine.",
            "",
            "<!-- MUR:START - Auto-generated by mur sync. Do not edit this section. -->",
            "## Learned Patterns",
            "",
            "### Old item",
            "old body",
            "",
            "<!-- MUR:END -->",
            "",
        ]
        .join("\n");
        std::fs::write(&path, &existing).unwrap();

        let content =
            generate_sync_content_from_items(&[make_item("New item")], &SyncFormat::Markdown);
        write_sync_file(&path, &content, &SyncFormat::Markdown).unwrap();

        let out = std::fs::read_to_string(&path).unwrap();
        assert!(
            out.contains("My Project"),
            "the user's own content survives"
        );
        assert!(out.contains("## Learned Skills"), "got:\n{out}");
        assert!(
            !out.contains("## Learned Patterns"),
            "the old heading must not linger beside the new one; got:\n{out}"
        );
        assert!(
            !out.contains("Old item"),
            "the whole marked region is replaced"
        );
    }

    /// A file we cannot READ must never be replaced. `read_to_string` fails the
    /// same way for a permission error as for a missing file, and treating the
    /// two alike swaps a hand-written document for the generated block alone —
    /// silent, total loss of the part of the file that is not ours.
    #[test]
    #[cfg(unix)]
    fn unreadable_target_is_refused_not_overwritten() {
        use std::os::unix::fs::PermissionsExt;

        let tmp = tempfile::TempDir::new().unwrap();
        let path = tmp.path().join("AGENTS.md");
        let original = "# My Project\n\nHand-written guidance.\n";
        std::fs::write(&path, original).unwrap();
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o000)).unwrap();

        let content =
            generate_sync_content_from_items(&[make_item("Pattern A")], &SyncFormat::Markdown);
        let err = write_sync_file(&path, &content, &SyncFormat::Markdown).unwrap_err();
        assert!(err.to_string().contains("before sync"), "{err}");

        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o644)).unwrap();
        assert_eq!(
            std::fs::read_to_string(&path).unwrap(),
            original,
            "a failed read must leave the file untouched"
        );
    }

    /// Reordered markers must not splice: `&existing[..start] + content +
    /// &existing[end..]` on a backwards pair duplicates the span between them
    /// instead of replacing it. Append instead — worst case is a stale block
    /// the user can delete, not mangled content.
    #[test]
    fn reversed_markers_append_instead_of_splicing() {
        let tmp = tempfile::TempDir::new().unwrap();
        let path = tmp.path().join("AGENTS.md");
        std::fs::write(
            &path,
            "# My Project\n<!-- MUR:END -->\nstranded\n<!-- MUR:START - Auto-generated by mur sync. Do not edit this section. -->\n",
        )
        .unwrap();

        let content =
            generate_sync_content_from_items(&[make_item("Pattern A")], &SyncFormat::Markdown);
        write_sync_file(&path, &content, &SyncFormat::Markdown).unwrap();

        let result = std::fs::read_to_string(&path).unwrap();
        assert!(result.contains("My Project"), "{result}");
        assert!(result.contains("stranded"), "{result}");
        assert!(result.contains("Pattern A"), "{result}");
    }

    /// The target is replaced by rename, so no reader ever sees a half-written
    /// file and no temp file is left behind.
    #[test]
    fn write_leaves_no_temp_file() {
        let tmp = tempfile::TempDir::new().unwrap();
        let path = tmp.path().join("AGENTS.md");
        std::fs::write(&path, "# My Project\n").unwrap();

        let content =
            generate_sync_content_from_items(&[make_item("Pattern A")], &SyncFormat::Markdown);
        write_sync_file(&path, &content, &SyncFormat::Markdown).unwrap();

        let leftovers: Vec<_> = std::fs::read_dir(tmp.path())
            .unwrap()
            .filter_map(|e| e.ok())
            .map(|e| e.file_name().to_string_lossy().into_owned())
            .filter(|n| n != "AGENTS.md")
            .collect();
        assert!(leftovers.is_empty(), "left behind: {leftovers:?}");
    }
}
