use anyhow::Result;
use std::fs;
use std::io::{self, Write};
use std::path::Path;

/// Drive an async future from a sync caller that's already inside the
/// `mur-main` multi-threaded tokio runtime (see `main.rs::main`).
///
/// `tokio::task::block_in_place` releases the current worker thread so we
/// can synchronously block on `Handle::current().block_on(future)`. We
/// cannot use `Runtime::new(...).block_on(...)` here because constructing a
/// new runtime inside an existing runtime panics ("Cannot start a runtime
/// from within a runtime").
fn block_on_in_runtime<F: std::future::Future>(future: F) -> F::Output {
    tokio::task::block_in_place(|| tokio::runtime::Handle::current().block_on(future))
}

/// Run embedding + LLM discovery against all detected local runtimes,
/// blocking the caller's thread. When `refresh` is true, the on-disk cache
/// is deleted first.
fn discover_blocking(refresh: bool) -> Result<Vec<crate::discovery::DiscoveredModel>> {
    if refresh {
        let cache_path = crate::discovery::cache::DiscoveryCache::default_path();
        let _ = std::fs::remove_file(&cache_path);
    }
    block_on_in_runtime(crate::discovery::run_all())
}

pub(crate) const HOOK_SCRIPT_PROMPT: &str = "#!/bin/bash
# mur-managed-hook v7 — generated by `mur init --hooks`
exec mur hook prompt --tool \"${MUR_TOOL:-claude}\"
";

pub(crate) const HOOK_SCRIPT_TOOL: &str = "#!/bin/bash
# mur-managed-hook v7 — generated by `mur init --hooks`
exec mur hook tool --tool \"${MUR_TOOL:-claude}\"
";

pub(crate) const HOOK_SCRIPT_STOP: &str = "#!/bin/bash
# mur-managed-hook v7 — generated by `mur init --hooks`
exec mur hook stop --tool \"${MUR_TOOL:-claude}\"
";

pub(crate) const HOOK_SCRIPT_SESSION_START: &str = "#!/bin/bash
# mur-managed-hook v7 — generated by `mur init --hooks`
exec mur hook session-start --tool \"${MUR_TOOL:-claude}\"
";

/// Derive Claude Code async flags for a given hook event name.
///
/// Returns `(async_flag, rewake_flag)`:
/// - `async_flag=true` for `UserPromptSubmit` (async execution)
/// - `rewake_flag=true` for `Stop` (async re-wake after completion)
/// - Both false for other events
fn hook_async_flags(event_name: &str) -> (bool, bool) {
    (
        matches!(event_name, "UserPromptSubmit"),
        matches!(event_name, "Stop"),
    )
}

pub(crate) fn cmd_init(hooks_flag: bool, refresh_discovery: bool) -> Result<()> {
    let home =
        dirs::home_dir().ok_or_else(|| anyhow::anyhow!("Cannot determine home directory"))?;
    let mur_dir = home.join(".mur");

    // ─── Step A: Create directory structure ───────────────────────
    let dirs_to_create = [
        mur_dir.clone(),
        mur_dir.join("patterns"),
        mur_dir.join("workflows"),
        mur_dir.join("session").join("recordings"),
        mur_dir.join("hooks"),
        mur_dir.join("index"),
    ];
    for d in &dirs_to_create {
        std::fs::create_dir_all(d)?;
    }

    // ─── Step E: Write default config.yaml if not exists ─────────
    let config_path = mur_dir.join("config.yaml");
    if !config_path.exists() {
        let cfg = mur_common::config::Config {
            fleet_run: starter_fleet_run(),
            ..Default::default()
        };
        crate::store::config::save_config(&cfg)?;
    } else {
        // Re-running init on an existing install: append the fleet_run
        // starter textually. NEVER load-modify-save here — the typed Config
        // drops foreign blocks other binaries own (e.g. `research_gateway:`).
        if append_fleet_run_if_absent(&config_path)? {
            println!("  ✓ Added starter fleet_run authorization to config.yaml");
        }
    }

    // ─── Determine whether to install hooks ──────────────────────
    let install_hooks = if hooks_flag {
        true
    } else {
        // Interactive prompt
        print!("Install hooks for AI tools? [Y/n] ");
        io::stdout().flush()?;
        let mut answer = String::new();
        io::stdin().read_line(&mut answer)?;
        let answer = answer.trim().to_lowercase();
        answer.is_empty() || answer == "y" || answer == "yes"
    };

    let mut hooks_installed = Vec::new();

    if install_hooks {
        // ─── Step B: Write hook scripts ──────────────────────────
        let on_prompt = HOOK_SCRIPT_PROMPT;
        let on_tool = HOOK_SCRIPT_TOOL;
        let on_stop = HOOK_SCRIPT_STOP;

        let hooks = [
            ("on-prompt.sh", on_prompt),
            ("on-tool.sh", on_tool),
            ("on-stop.sh", on_stop),
            ("on-session-start.sh", HOOK_SCRIPT_SESSION_START),
        ];

        for (filename, content) in &hooks {
            let path = mur_dir.join("hooks").join(filename);
            std::fs::write(&path, content)?;
            // Make executable
            #[cfg(unix)]
            {
                use std::os::unix::fs::PermissionsExt;
                std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o755))?;
            }
        }

        // ─── Step C: Install Claude Code hooks in settings.json ──
        let claude_dir = home.join(".claude");
        std::fs::create_dir_all(&claude_dir)?;
        let settings_path = claude_dir.join("settings.json");

        let mut settings: serde_json::Value = if settings_path.exists() {
            let content = std::fs::read_to_string(&settings_path)?;
            serde_json::from_str(&content).unwrap_or_else(|_| serde_json::json!({}))
        } else {
            serde_json::json!({})
        };

        let hooks_dir = mur_dir.join("hooks");
        let mur_hook_marker = "mur-managed-hook";

        // Define the hooks we want to install
        let hook_defs = [
            (
                "UserPromptSubmit",
                hooks_dir.join("on-prompt.sh").to_string_lossy().to_string(),
            ),
            (
                "PreToolUse",
                hooks_dir.join("on-tool.sh").to_string_lossy().to_string(),
            ),
            (
                "PostToolUse",
                hooks_dir.join("on-tool.sh").to_string_lossy().to_string(),
            ),
            (
                "Stop",
                hooks_dir.join("on-stop.sh").to_string_lossy().to_string(),
            ),
            (
                "SessionStart",
                hooks_dir
                    .join("on-session-start.sh")
                    .to_string_lossy()
                    .to_string(),
            ),
        ];

        let hooks_obj = settings
            .as_object_mut()
            .ok_or_else(|| anyhow::anyhow!("Claude settings.json is not a JSON object"))?
            .entry("hooks")
            .or_insert_with(|| serde_json::json!({}));

        for (event_name, script_path) in &hook_defs {
            let event_arr = hooks_obj
                .as_object_mut()
                .ok_or_else(|| anyhow::anyhow!("hooks field is not a JSON object"))?
                .entry(*event_name)
                .or_insert_with(|| serde_json::json!([]));

            let arr = event_arr
                .as_array_mut()
                .ok_or_else(|| anyhow::anyhow!("hook event '{event_name}' is not an array"))?;

            // Remove any existing mur-managed hooks (by checking command contains mur hooks dir)
            arr.retain(|entry| {
                // Check flat format: { command: "..." }
                if let Some(cmd) = entry.get("command").and_then(|c| c.as_str()) {
                    return !cmd.contains(mur_hook_marker) && !cmd.contains(".mur/hooks/");
                }
                // Check nested format: { hooks: [{ command: "..." }] }
                if let Some(hooks) = entry.get("hooks").and_then(|h| h.as_array()) {
                    return !hooks.iter().any(|h| {
                        h.get("command")
                            .and_then(|c| c.as_str())
                            .map(|c| c.contains(".mur/hooks/"))
                            .unwrap_or(false)
                    });
                }
                true
            });

            // Add our hook with Claude Code async flags
            let (async_flag, rewake_flag) = hook_async_flags(event_name);
            let mut hook_entry = serde_json::json!({
                "hooks": [{
                    "type": "command",
                    "command": format!("bash {}", script_path),
                }],
                "matcher": ""
            });
            if async_flag {
                hook_entry["hooks"][0]["async"] = serde_json::json!(true);
            }
            if rewake_flag {
                hook_entry["hooks"][0]["asyncRewake"] = serde_json::json!(true);
            }
            arr.push(hook_entry);
        }

        // Write settings back with pretty formatting
        let pretty = serde_json::to_string_pretty(&settings)?;
        std::fs::write(&settings_path, pretty)?;

        hooks_installed.push("Claude Code");

        // Install murmurd as login service
        let murmurd_bin = super::init_daemon::murmurd_bin_path();
        match super::init_daemon::install_daemon_service(&murmurd_bin) {
            Ok(true) => println!("  murmurd autostart installed (login service)."),
            Ok(false) => println!(
                "  murmurd autostart: unsupported platform.\n  Run `mur murmurd start --detach` manually."
            ),
            Err(e) => eprintln!("  murmurd install warning: {e:#}"),
        }
    }

    // ─── Step C2: Install Auggie hooks in settings.json ──────────
    let auggie_dir = home.join(".augment");
    if auggie_dir.exists() {
        let auggie_settings_path = auggie_dir.join("settings.json");
        let mut auggie_settings: serde_json::Value = if auggie_settings_path.exists() {
            let data = std::fs::read_to_string(&auggie_settings_path)?;
            serde_json::from_str(&data).unwrap_or(serde_json::json!({}))
        } else {
            serde_json::json!({})
        };

        let hooks_dir = mur_dir.join("hooks");
        let prompt_script = hooks_dir.join("on-prompt.sh");
        let tool_script = hooks_dir.join("on-tool.sh");
        let stop_script = hooks_dir.join("on-stop.sh");

        // Auggie supports full Claude Code-compatible hooks:
        // PreToolUse, PostToolUse, Stop, SessionStart, SessionEnd
        let mur_hooks = serde_json::json!({
            "PreToolUse": [{
                "hooks": [{"type": "command", "command": format!("bash {}", prompt_script.display())}],
                "matcher": ""
            }],
            "PostToolUse": [{
                "hooks": [{"type": "command", "command": format!("bash {}", tool_script.display())}],
                "matcher": ""
            }],
            "Stop": [{
                "hooks": [{"type": "command", "command": format!("bash {}", stop_script.display())}]
            }]
        });

        // Merge: preserve existing hooks, overwrite mur-managed ones
        let existing_hooks = auggie_settings
            .get("hooks")
            .cloned()
            .unwrap_or(serde_json::json!({}));
        let mut merged = existing_hooks.as_object().cloned().unwrap_or_default();
        if let Some(mur_obj) = mur_hooks.as_object() {
            for (k, v) in mur_obj {
                merged.insert(k.clone(), v.clone());
            }
        }
        auggie_settings["hooks"] = serde_json::Value::Object(merged);

        let pretty = serde_json::to_string_pretty(&auggie_settings)?;
        std::fs::write(&auggie_settings_path, pretty)?;
        hooks_installed.push("Auggie");
    }

    // ─── Step C3: Install Gemini CLI hooks in settings.json ──────
    let gemini_dir = home.join(".gemini");
    if gemini_dir.exists() {
        let gemini_settings_path = gemini_dir.join("settings.json");
        let mut gemini_settings: serde_json::Value = if gemini_settings_path.exists() {
            let data = std::fs::read_to_string(&gemini_settings_path)?;
            serde_json::from_str(&data).unwrap_or(serde_json::json!({}))
        } else {
            serde_json::json!({})
        };

        let hooks_dir = mur_dir.join("hooks");
        let prompt_script = hooks_dir.join("on-prompt.sh");
        let stop_script = hooks_dir.join("on-stop.sh");

        let tool_script = hooks_dir.join("on-tool.sh");

        // Gemini CLI v0.26.0+ hook events
        let mur_hooks = serde_json::json!({
            "BeforeAgent": [{
                "hooks": [{"type": "command", "command": format!("bash {}", prompt_script.display())}]
            }],
            "AfterTool": [{
                "hooks": [{"type": "command", "command": format!("bash {}", tool_script.display())}]
            }],
            "SessionEnd": [{
                "hooks": [{"type": "command", "command": format!("bash {}", stop_script.display())}]
            }]
        });

        let existing_hooks = gemini_settings
            .get("hooks")
            .cloned()
            .unwrap_or(serde_json::json!({}));
        let mut merged = existing_hooks.as_object().cloned().unwrap_or_default();
        if let Some(mur_obj) = mur_hooks.as_object() {
            for (k, v) in mur_obj {
                merged.insert(k.clone(), v.clone());
            }
        }
        gemini_settings["hooks"] = serde_json::Value::Object(merged);

        let pretty = serde_json::to_string_pretty(&gemini_settings)?;
        std::fs::write(&gemini_settings_path, pretty)?;
        hooks_installed.push("Gemini CLI");
    }

    // ─── Step C4: Install GitHub Copilot CLI hooks ───────────────
    // Copilot CLI (GA 2026-02-25) reads hooks from:
    //   - ~/.github/hooks.json (global)
    //   - .github/hooks.json (project-level)
    // Format: { version: 1, hooks: { eventName: [{ type, bash, timeoutSec }] } }
    // Events: sessionStart, sessionEnd, userPromptSubmitted, preToolUse, postToolUse
    let copilot_hooks_dir = home.join(".github");
    {
        std::fs::create_dir_all(&copilot_hooks_dir)?;
        let hooks_dir = mur_dir.join("hooks");
        let prompt_script = hooks_dir.join("on-prompt.sh");
        let tool_script = hooks_dir.join("on-tool.sh");
        let stop_script = hooks_dir.join("on-stop.sh");

        let hooks_path = copilot_hooks_dir.join("hooks.json");
        let mut hooks_json: serde_json::Value = if hooks_path.exists() {
            let data = std::fs::read_to_string(&hooks_path)?;
            serde_json::from_str(&data).unwrap_or(serde_json::json!({"version": 1, "hooks": {}}))
        } else {
            serde_json::json!({"version": 1, "hooks": {}})
        };

        let mur_marker = ".mur/hooks/";
        let hook_defs = [
            ("sessionStart", format!("bash {}", prompt_script.display())),
            (
                "userPromptSubmitted",
                format!("bash {}", prompt_script.display()),
            ),
            ("postToolUse", format!("bash {}", tool_script.display())),
            ("sessionEnd", format!("bash {}", stop_script.display())),
        ];

        let hooks_obj = hooks_json
            .as_object_mut()
            .ok_or_else(|| anyhow::anyhow!("Copilot hooks.json is not a JSON object"))?
            .entry("hooks")
            .or_insert_with(|| serde_json::json!({}));

        for (event_name, script_cmd) in &hook_defs {
            let event_arr = hooks_obj
                .as_object_mut()
                .ok_or_else(|| anyhow::anyhow!("hooks field is not a JSON object"))?
                .entry(*event_name)
                .or_insert_with(|| serde_json::json!([]));
            let arr = event_arr
                .as_array_mut()
                .ok_or_else(|| anyhow::anyhow!("hook event '{event_name}' is not an array"))?;
            // Remove existing mur hooks
            arr.retain(|entry| {
                entry
                    .get("bash")
                    .and_then(|c| c.as_str())
                    .map(|c| !c.contains(mur_marker))
                    .unwrap_or(true)
            });
            arr.push(serde_json::json!({
                "type": "command",
                "bash": script_cmd,
                "comment": "mur-managed-hook",
                "timeoutSec": 30
            }));
        }

        let pretty = serde_json::to_string_pretty(&hooks_json)?;
        std::fs::write(&hooks_path, pretty)?;
        hooks_installed.push("Copilot CLI");
    }

    // ─── Step C5: OpenClaw ──────────────────────────────────────
    // OpenClaw skills are handled via symlinks in ensure_mur_skill (Step C11).
    // Detection is handled in the detected tools section below.

    // ─── Step C6: Install Cursor hooks ────────────────────────────
    let cursor_dir = home.join(".cursor");
    if cursor_dir.exists() {
        let hooks_dir = mur_dir.join("hooks");
        let prompt_script = hooks_dir.join("on-prompt.sh");
        let tool_script = hooks_dir.join("on-tool.sh");
        let stop_script = hooks_dir.join("on-stop.sh");

        let cursor_hooks_path = cursor_dir.join("hooks.json");
        let mut cursor_hooks: serde_json::Value = if cursor_hooks_path.exists() {
            let data = std::fs::read_to_string(&cursor_hooks_path)?;
            serde_json::from_str(&data).unwrap_or(serde_json::json!({"version": 1, "hooks": {}}))
        } else {
            serde_json::json!({"version": 1, "hooks": {}})
        };

        let mur_hook_marker = "mur-managed-hook";

        // Cursor hooks format: { version: 1, hooks: { eventName: [{ command: "..." }] } }
        let hook_defs = [
            (
                "beforeSubmitPrompt",
                prompt_script.to_string_lossy().to_string(),
            ),
            (
                "beforeShellExecution",
                tool_script.to_string_lossy().to_string(),
            ),
            ("stop", stop_script.to_string_lossy().to_string()),
        ];

        let hooks_obj = cursor_hooks
            .as_object_mut()
            .ok_or_else(|| anyhow::anyhow!("Cursor hooks.json is not a JSON object"))?
            .entry("hooks")
            .or_insert_with(|| serde_json::json!({}));

        for (event_name, script_path) in &hook_defs {
            let event_arr = hooks_obj
                .as_object_mut()
                .ok_or_else(|| anyhow::anyhow!("hooks field is not a JSON object"))?
                .entry(*event_name)
                .or_insert_with(|| serde_json::json!([]));
            let arr = event_arr
                .as_array_mut()
                .ok_or_else(|| anyhow::anyhow!("hook event '{event_name}' is not an array"))?;
            arr.retain(|entry| {
                entry
                    .get("command")
                    .and_then(|c| c.as_str())
                    .map(|c| !c.contains(mur_hook_marker) && !c.contains(".mur/hooks/"))
                    .unwrap_or(true)
            });
            arr.push(serde_json::json!({
                "command": format!("bash {}", script_path)
            }));
        }

        let pretty = serde_json::to_string_pretty(&cursor_hooks)?;
        std::fs::write(&cursor_hooks_path, pretty)?;
        hooks_installed.push("Cursor");
    }

    // ─── Step C7: Install Codex CLI integration ──────────────────
    let codex_dir = home.join(".codex");
    if codex_dir.exists() {
        // Codex reads AGENTS.md — we add a mur context section
        // Also set developer_instructions in config.toml
        let config_path = codex_dir.join("config.toml");
        if config_path.exists() {
            let mut config_content = std::fs::read_to_string(&config_path)?;
            let mur_instruction = "# mur-managed: inject learning context\n# Run `mur context --compact` before sessions for pattern injection\n";
            if !config_content.contains("mur-managed") {
                config_content.push_str(&format!(
                    "\n{}\ndeveloper_instructions = \"Before coding, check if mur has relevant patterns: run `mur context --compact` in the project directory.\"\n",
                    mur_instruction
                ));
                std::fs::write(&config_path, config_content)?;
            }
        }
        hooks_installed.push("Codex CLI");
    }

    // ─── Step C8a: Install OpenCode plugin ─────────────────────────
    // OpenCode uses JS/TS plugins in ~/.config/opencode/plugins/
    let opencode_plugins = home.join(".config").join("opencode").join("plugins");
    if home.join(".config").join("opencode").exists()
        || std::process::Command::new("which")
            .arg("opencode")
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
    {
        std::fs::create_dir_all(&opencode_plugins)?;
        let plugin_path = opencode_plugins.join("mur-plugin.ts");
        let hooks_dir = mur_dir.join("hooks");
        let plugin_content = format!(
            r#"// MUR learning plugin for OpenCode
// Auto-generated by `mur init --hooks`
import {{ execSync }} from "child_process";

export const MurPlugin = async ({{ project, $ }}) => {{
  // Inject MUR context at session start
  try {{
    execSync("bash {on_prompt}", {{ stdio: "pipe", timeout: 30000 }});
  }} catch (_) {{}}

  return {{
    "session.created": async (_input) => {{
      try {{
        execSync("bash {on_prompt}", {{ stdio: "pipe", timeout: 30000 }});
      }} catch (_) {{}}
    }},
    "tool.execute.after": async (_input) => {{
      try {{
        execSync("bash {on_tool}", {{ stdio: "pipe", timeout: 10000 }});
      }} catch (_) {{}}
    }},
    "session.updated": async (input) => {{
      // On session end, trigger learning
      if (input?.status === "complete" || input?.status === "error") {{
        try {{
          execSync("bash {on_stop}", {{ stdio: "pipe", timeout: 30000 }});
        }} catch (_) {{}}
      }}
    }},
  }};
}};
"#,
            on_prompt = hooks_dir.join("on-prompt.sh").display(),
            on_tool = hooks_dir.join("on-tool.sh").display(),
            on_stop = hooks_dir.join("on-stop.sh").display(),
        );
        std::fs::write(&plugin_path, plugin_content)?;
        hooks_installed.push("OpenCode");
    }

    // ─── Step C8b: Install Amp hooks ──────────────────────────────
    // Amp uses Claude Code hook format in AGENTS.md frontmatter or ~/.amp/hooks.json
    // Also supports .agents/skills/ for skills
    let amp_exists = std::process::Command::new("which")
        .arg("amp")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false);
    if amp_exists {
        let amp_dir = home.join(".amp");
        std::fs::create_dir_all(&amp_dir)?;
        let hooks_dir = mur_dir.join("hooks");
        let prompt_script = hooks_dir.join("on-prompt.sh");
        let tool_script = hooks_dir.join("on-tool.sh");
        let stop_script = hooks_dir.join("on-stop.sh");

        // Amp uses same format as Claude Code hooks
        let hooks_path = amp_dir.join("hooks.json");
        let amp_hooks = serde_json::json!({
            "hooks": {
                "PreToolUse": [{
                    "hooks": [{"type": "command", "command": format!("bash {}", prompt_script.display())}],
                    "matcher": ""
                }],
                "PostToolUse": [{
                    "hooks": [{"type": "command", "command": format!("bash {}", tool_script.display())}],
                    "matcher": ""
                }],
                "Stop": [{
                    "hooks": [{"type": "command", "command": format!("bash {}", stop_script.display())}],
                    "matcher": ""
                }]
            }
        });
        let pretty = serde_json::to_string_pretty(&amp_hooks)?;
        std::fs::write(&hooks_path, pretty)?;
        hooks_installed.push("Amp");
    }

    // ─── Step C9: Generate context files for file-based tools ────
    // Aider, Cline, Windsurf, Amazon Q use file-based instructions
    // Generate a shared mur context file that can be referenced
    let mur_context_path = mur_dir.join("context.md");
    let mur_context = r#"# MUR Context
# Auto-generated by `mur init --hooks`. Updated by `mur context --file`.
# This file is referenced by Aider, Cline, Windsurf, and other file-based tools.

## How to use MUR with this tool

MUR captures learning patterns from your coding sessions.
Run `mur context` to see relevant patterns for your current project.
Run `mur search <query>` to find specific patterns.
Run `mur learn` to extract new patterns from recent sessions.

## Quick reference

- Patterns: ~/.mur/patterns/
- Workflows: ~/.mur/workflows/
- Dashboard: `mur serve --open`
"#;
    std::fs::write(&mur_context_path, mur_context)?;

    // Aider: add to .aider.conf.yml if it exists
    let aider_conf = home.join(".aider.conf.yml");
    if aider_conf.exists() {
        let content = std::fs::read_to_string(&aider_conf)?;
        if !content.contains(".mur/context.md") {
            let mut new_content = content;
            new_content.push_str(&format!(
                "\n# mur-managed: auto-load learning context\nread:\n  - {}\n",
                mur_context_path.display()
            ));
            std::fs::write(&aider_conf, new_content)?;
            hooks_installed.push("Aider");
        }
    } else {
        // Create minimal .aider.conf.yml
        let aider_config = format!(
            "# mur-managed: auto-load learning context\nread:\n  - {}\n",
            mur_context_path.display()
        );
        std::fs::write(&aider_conf, aider_config)?;
        hooks_installed.push("Aider");
    }

    // ─── Step C10: Detect and print setup hints for file-based tools ─
    // Zed reads: .rules > .cursorrules > .windsurfrules > AGENTS.md (first match wins)
    // Junie reads: .junie/guidelines.md
    // Trae reads: .trae/rules/
    // These are project-level, so we just print hints
    let file_based_hints: Vec<(&str, &str)> = vec![
        (
            "Zed",
            "Add `See ~/.mur/context.md` to your AGENTS.md or .rules file",
        ),
        (
            "Junie",
            "Add `See ~/.mur/context.md` to .junie/guidelines.md",
        ),
        ("Trae", "Add `See ~/.mur/context.md` to .trae/rules/mur.md"),
        ("Cline/Roo", "Add `See ~/.mur/context.md` to .clinerules"),
        ("Windsurf", "Add `See ~/.mur/context.md` to .windsurfrules"),
    ];

    // ─── Step C11: Install AI tool skills ────────────────────────
    // Skills teach AI tools about mur commands and how to interact
    // with the pattern system (feedback, create, search, etc.)
    if install_hooks {
        let _ = super::sync_cmd::ensure_mur_skill(&home, &mur_common::trust::mur_home());
    }

    // ─── Step G: Model setup (one question) ─────────────────────────
    println!();
    println!("Model setup:");
    let discovered = discover_blocking(refresh_discovery).unwrap_or_default();
    let mut keys = crate::model_setup::probe_env_keys();
    if let Ok(reg_path) = mur_common::model::ModelRegistry::default_path()
        && let Ok(reg) = mur_common::model::ModelRegistry::load_from(&reg_path)
    {
        keys.extend(crate::model_setup::keychain_key_sources(&reg));
    }
    let plan = crate::model_setup::recommend(&discovered, &keys);
    println!(
        "  1) Use recommended defaults — {}  (default)",
        plan.summary
    );
    println!("  2) Configure later in MUR Hub (Settings → Models)");
    print!("Choose [1/2] (default: 1): ");
    io::stdout().flush()?;
    let mut model_choice = String::new();
    io::stdin().read_line(&mut model_choice)?;
    let mut config = crate::store::config::load_config()?;
    if model_choice.trim() == "2" || plan.smart.is_none() {
        println!("  Skipped. Open MUR Hub → Settings → Models to configure models.");
    } else {
        crate::model_setup::apply(&plan, &mut config);
        crate::store::config::save_config(&config)?;
        println!("  ✓ {}", plan.summary);
    }

    // ─── Step H: Community sharing opt-in ──────────────────────────
    println!();
    print!("Enable community pattern sharing? [y/N] ");
    io::stdout().flush()?;
    let mut community_answer = String::new();
    io::stdin().read_line(&mut community_answer)?;
    let community_enabled = {
        let a = community_answer.trim().to_lowercase();
        a == "y" || a == "yes"
    };

    if community_enabled {
        // Reload config in case model setup saved changes
        config = crate::store::config::load_config().unwrap_or(config);
        config.community.enabled = true;
        let _ = crate::store::config::save_config(&config);
        println!("  Community sharing enabled.");
        println!("  Run `mur auth login` to authenticate and start sharing patterns.");
    }

    // ─── Step I: Device sync setup ──────────────────────────────
    println!();
    println!("Device sync — keep patterns in sync across machines:");
    println!();
    println!("  1) Cloud sync (recommended)");
    println!("     Auto conflict resolution, 3-month free trial, just works.");
    println!("  2) Git sync (free)");
    println!("     Use your own git repo to sync ~/.mur/patterns/");
    println!("  3) Skip (local only)");
    print!("Choose [1/2/3] (default: 1): ");
    io::stdout().flush()?;
    let mut sync_choice = String::new();
    io::stdin().read_line(&mut sync_choice)?;
    let sync_choice = sync_choice.trim();

    config = crate::store::config::load_config().unwrap_or(config);

    match sync_choice {
        "" | "1" => {
            config.sync.method = "cloud".to_string();
            config.sync.auto = true;
            config.sync.git_remote = None;
            crate::store::config::save_config(&config)?;
            println!("  ✓ Cloud sync enabled (auto-sync on).");
            println!("  Run `mur auth login` to authenticate and activate sync.");
        }
        "2" => {
            config.sync.method = "git".to_string();
            config.sync.auto = true;
            print!("  Git remote URL (e.g. git@github.com:you/mur-data.git): ");
            io::stdout().flush()?;
            let mut remote_url = String::new();
            io::stdin().read_line(&mut remote_url)?;
            let remote_url = remote_url.trim().to_string();
            if !remote_url.is_empty() {
                config.sync.git_remote = Some(remote_url.clone());
                println!("  ✓ Git sync enabled with remote: {}", remote_url);
            } else {
                println!(
                    "  ⚠ No remote URL provided. Set sync.git_remote in ~/.mur/config.yaml later."
                );
            }
            crate::store::config::save_config(&config)?;
        }
        _ => {
            config.sync.method = "local".to_string();
            config.sync.auto = false;
            config.sync.git_remote = None;
            crate::store::config::save_config(&config)?;
            println!("  Keeping local only. Run `mur init` again to enable sync later.");
        }
    }

    // ─── Step D: Detect other tools ──────────────────────────────
    let gemini_settings = home.join(".gemini").join("settings.json");
    let cursor_rules = std::env::current_dir().ok().map(|d| d.join(".cursorrules"));

    let mut detected_tools = Vec::new();

    if gemini_settings.exists() || home.join(".gemini").exists() {
        detected_tools.push("Gemini CLI");
        // Antigravity uses Gemini under the hood — same hooks apply
        detected_tools.push("Antigravity");
    }
    if let Some(ref cr) = cursor_rules
        && cr.exists()
    {
        detected_tools.push("Cursor");
    }

    // Check for CLI-based AI tools via `which`
    let cli_tools = [
        ("codex", "Codex"),
        ("auggie", "Auggie"),
        ("aider", "Aider"),
        ("openclaw", "OpenClaw"),
        ("opencode", "OpenCode"),
        ("amp", "Amp"),
        ("zed", "Zed"),
    ];
    for (binary, name) in &cli_tools {
        if std::process::Command::new("which")
            .arg(binary)
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
        {
            detected_tools.push(name);
        }
    }

    // Check for GitHub Copilot config directory
    if home.join(".config").join("github-copilot").exists() || home.join(".copilot").exists() {
        detected_tools.push("GitHub Copilot");
    }

    // Check for Cline/Roo (VS Code extension — detect .clinerules in cwd)
    if let Ok(cwd) = std::env::current_dir()
        && (cwd.join(".clinerules").exists() || cwd.join(".roomodes").exists())
    {
        detected_tools.push("Cline/Roo");
    }

    // Check for Windsurf
    if let Ok(cwd) = std::env::current_dir()
        && (cwd.join(".windsurfrules").exists() || cwd.join(".windsurf").exists())
    {
        detected_tools.push("Windsurf");
    }

    // Check for Amazon Q
    if home.join(".amazonq").exists() {
        detected_tools.push("Amazon Q");
    }

    // Check for JetBrains Junie
    if let Ok(cwd) = std::env::current_dir() {
        if cwd.join(".junie").exists() {
            detected_tools.push("Junie");
        }
        if cwd.join(".trae").exists() {
            detected_tools.push("Trae");
        }
    }

    // ─── Step F: Print summary ───────────────────────────────────
    let pattern_count = if mur_dir.join("patterns").exists() {
        std::fs::read_dir(mur_dir.join("patterns"))
            .map(|entries| {
                entries
                    .filter_map(|e| e.ok())
                    .filter(|e| {
                        e.path()
                            .extension()
                            .map(|ext| ext == "yaml" || ext == "yml")
                            .unwrap_or(false)
                    })
                    .count()
            })
            .unwrap_or(0)
    } else {
        0
    };

    println!();
    println!("✅ MUR initialized!");
    println!();
    println!("  📁 Data directory: ~/.mur/");
    if !hooks_installed.is_empty() {
        println!("  🪝 Hooks installed: {}", hooks_installed.join(", "));
    } else {
        println!("  🪝 Hooks: not installed (run `mur init --hooks` to install)");
    }
    println!(
        "  📝 Patterns: {} {}",
        pattern_count,
        if pattern_count == 0 {
            "(run `mur new` to create your first)"
        } else {
            ""
        }
    );

    // Show detected tools
    if !detected_tools.is_empty() {
        println!();
        println!("  🔍 Detected tools: {}", detected_tools.join(", "));
    }

    // Show file-based tool hints
    let show_hints: Vec<_> = file_based_hints
        .iter()
        .filter(|(tool, _)| detected_tools.contains(tool))
        .collect();
    if !show_hints.is_empty() {
        println!();
        println!("  📝 File-based tools (add MUR context manually):");
        for (tool, hint) in &show_hints {
            println!("    💡 {}: {}", tool, hint);
        }
    }

    println!();
    println!("  Next steps:");
    println!("    1. Start coding — MUR injects patterns automatically via hooks");
    println!("    2. Run `mur context --file` to update context for file-based tools");
    println!("    3. Run `mur search <query>` to find patterns");
    if community_enabled {
        println!("    4. Run `mur auth login` to authenticate for community sharing");
        println!("    5. Run `mur community list` to browse community patterns");
    }
    println!();

    Ok(())
}

/// Starter `fleet_run` authorization seeded by `mur init`: the concierge may
/// trigger the deep-research fleet. Still inert until that fleet exists AND
/// has a positive `loop.budget_usd` (the tool refuses otherwise), so seeding
/// it costs nothing on a fresh install but saves the "why can't murmur run
/// deep-research" round-trip later.
fn starter_fleet_run() -> mur_common::config::FleetRunConfig {
    mur_common::config::FleetRunConfig {
        agents: vec![mur_common::fleet::CONCIERGE_AGENT.to_string()],
        fleets: vec![crate::cmd::deep_research::status::DEFAULT_FLEET_NAME.to_string()],
    }
}

/// Append the starter `fleet_run:` block to an existing config.yaml, unless a
/// `fleet_run:` key is already present (user-authored settings are never
/// touched). Returns whether the block was appended. Textual append on
/// purpose: round-tripping through the typed `Config` would drop foreign
/// top-level blocks owned by other binaries (e.g. `research_gateway:`).
/// Also called by `mur deep-research setup` (the other consent moment).
pub(crate) fn append_fleet_run_if_absent(config_path: &Path) -> Result<bool> {
    let text = fs::read_to_string(config_path)?;
    if text
        .lines()
        .any(|l| l.trim_start().starts_with("fleet_run:"))
    {
        return Ok(false);
    }
    let starter = starter_fleet_run();
    let mut out = text;
    if !out.is_empty() && !out.ends_with('\n') {
        out.push('\n');
    }
    out.push_str(&format!(
        "\n# fleet_run built-in tool authorization (deny-by-default allowlists;\n\
         # lets the listed agents trigger the listed fleets from inside their sandbox)\n\
         fleet_run:\n  agents: [{}]\n  fleets: [{}]\n",
        starter.agents.join(", "),
        starter.fleets.join(", ")
    ));
    fs::write(config_path, out)?;
    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn starter_fleet_run_seeds_concierge_deep_research() {
        let s = starter_fleet_run();
        assert_eq!(s.agents, vec!["mur"]);
        assert_eq!(s.fleets, vec!["deep-research"]);
    }

    #[test]
    fn append_fleet_run_respects_existing_key_and_foreign_blocks() {
        let tmp = tempfile::tempdir().unwrap();
        let p = tmp.path().join("config.yaml");

        // Absent → appended, foreign block preserved.
        std::fs::write(&p, "research_gateway:\n  brave_api_key: \"x\"").unwrap();
        assert!(append_fleet_run_if_absent(&p).unwrap());
        let text = std::fs::read_to_string(&p).unwrap();
        assert!(text.contains("research_gateway:"), "foreign block kept");
        assert!(text.contains("fleet_run:"));
        let cfg: mur_common::config::Config = serde_yaml_ng::from_str(&text).unwrap();
        assert_eq!(cfg.fleet_run.agents, vec!["mur"]);
        assert_eq!(cfg.fleet_run.fleets, vec!["deep-research"]);

        // Present (user-authored) → untouched.
        std::fs::write(&p, "fleet_run:\n  agents: [custom]\n  fleets: []\n").unwrap();
        assert!(!append_fleet_run_if_absent(&p).unwrap());
        let text = std::fs::read_to_string(&p).unwrap();
        assert_eq!(text.matches("fleet_run:").count(), 1);
        assert!(text.contains("custom"));
    }

    #[test]
    fn hook_scripts_use_unified_entry() {
        assert!(
            HOOK_SCRIPT_PROMPT.contains("mur hook prompt"),
            "on-prompt.sh must call mur hook prompt"
        );
        assert!(
            !HOOK_SCRIPT_PROMPT.contains("mur context"),
            "on-prompt.sh must NOT call mur context"
        );
        assert!(
            HOOK_SCRIPT_TOOL.contains("mur hook tool"),
            "on-tool.sh must call mur hook tool"
        );
        assert!(
            HOOK_SCRIPT_STOP.contains("mur hook stop"),
            "on-stop.sh must call mur hook stop"
        );
        assert!(
            HOOK_SCRIPT_SESSION_START.contains("mur hook session-start"),
            "on-session-start.sh must call mur hook session-start"
        );
        assert!(
            HOOK_SCRIPT_PROMPT.contains("v7"),
            "hook scripts must be version v7"
        );
    }
}

#[cfg(test)]
mod refresh_flag_tests {
    /// Compile-time check that `cmd_init` accepts the new `refresh_discovery` flag.
    #[test]
    fn cmd_init_accepts_refresh_discovery() {
        let _ = super::cmd_init as fn(bool, bool) -> anyhow::Result<()>;
    }
}

#[cfg(test)]
mod cloud_embedding_tests {
    use crate::store::embedding::{EmbeddingConfig, EmbeddingProvider};
    use mur_common::config::Config;

    /// When user picks Anthropic as cloud LLM and Voyage as embedding,
    /// embedding.openai_url must be None (Voyage uses its own canonical
    /// URL, not OpenRouter's).
    #[test]
    fn cloud_embedding_does_not_inherit_llm_openai_url() {
        let mut cfg = Config::default();
        cfg.llm.provider = "openai".into();
        cfg.llm.openai_url = Some("https://openrouter.ai/api/v1".into());
        // simulate what select_cloud_embedding does for anthropic→voyage:
        cfg.embedding.provider = "anthropic".into();
        cfg.embedding.model = "voyage-3-lite".into();
        cfg.embedding.api_key_env = Some("ANTHROPIC_API_KEY".into());
        cfg.embedding.openai_url = None;

        // Round-trip through EmbeddingConfig — should resolve OpenAI variant
        // with default base_url (api.openai.com), NOT OpenRouter.
        let ec = EmbeddingConfig::from_config(&cfg);
        match ec.provider {
            EmbeddingProvider::OpenAI { base_url, .. } => {
                assert_eq!(base_url, "https://api.openai.com/v1");
            }
            _ => panic!("expected OpenAI variant"),
        }
    }
}

#[cfg(test)]
mod runtime_regression_tests {
    //! Regression: `discover_blocking` and the dims-probe path are called
    //! synchronously from `cmd_init`, which itself runs inside the
    //! mur-main multi-threaded tokio runtime (see `main.rs::main`).
    //!
    //! Earlier M5 code constructed a NEW `tokio::runtime::Runtime` and
    //! called `.block_on(...)` on it — that panics with "Cannot start a
    //! runtime from within a runtime" because runtime construction inside
    //! an existing runtime is forbidden. The fix uses
    //! `tokio::task::block_in_place` + `Handle::current().block_on`.
    //!
    //! These tests reproduce the original panic conditions to make sure
    //! the bug doesn't return.
    use super::*;

    #[tokio::test(flavor = "multi_thread", worker_threads = 2)]
    async fn block_on_in_runtime_does_not_panic_inside_existing_runtime() {
        // The bug: building a new Runtime here would panic.
        // The fix: block_on_in_runtime uses Handle::current().block_on
        // via block_in_place, which is safe.
        let result = block_on_in_runtime(async { 42 });
        assert_eq!(result, 42);
    }

    #[tokio::test(flavor = "multi_thread", worker_threads = 2)]
    async fn discover_blocking_does_not_panic_inside_existing_runtime() {
        // discover_blocking calls block_on_in_runtime; this is the exact
        // path cmd_init runs through. Either no local runtimes are detected
        // (returns empty Vec) or some are present (returns their models) —
        // either way it must not panic.
        let result = discover_blocking(false);
        assert!(
            result.is_ok(),
            "discover_blocking should not error inside a tokio runtime: {:?}",
            result.err()
        );
    }
}

#[cfg(test)]
mod claude_hook_flags_tests {
    use super::hook_async_flags;
    use std::collections::HashMap;

    #[test]
    fn claude_hooks_have_async_flags() {
        let events = [
            "UserPromptSubmit",
            "PreToolUse",
            "PostToolUse",
            "Stop",
            "SessionStart",
        ];
        let mut results: HashMap<&str, serde_json::Value> = HashMap::new();
        for event_name in events {
            let (async_flag, rewake_flag) = hook_async_flags(event_name);
            let mut hook_entry = serde_json::json!({
                "hooks": [{"type": "command", "command": "bash /tmp/hook.sh"}],
                "matcher": ""
            });
            if async_flag {
                hook_entry["hooks"][0]["async"] = serde_json::json!(true);
            }
            if rewake_flag {
                hook_entry["hooks"][0]["asyncRewake"] = serde_json::json!(true);
            }
            results.insert(event_name, hook_entry);
        }
        assert_eq!(
            results["UserPromptSubmit"]["hooks"][0]["async"],
            serde_json::json!(true)
        );
        assert_eq!(
            results["Stop"]["hooks"][0]["asyncRewake"],
            serde_json::json!(true)
        );
        assert!(results["PreToolUse"]["hooks"][0].get("async").is_none());
        assert!(
            results["PostToolUse"]["hooks"][0]
                .get("asyncRewake")
                .is_none()
        );
        assert!(
            results["SessionStart"]["hooks"][0].get("async").is_none(),
            "SessionStart should not have async flag"
        );
        assert!(
            results["SessionStart"]["hooks"][0]
                .get("asyncRewake")
                .is_none(),
            "SessionStart should not have asyncRewake flag"
        );
    }
}
